######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 30 10:32:02 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += button.h dragonball.h inputreader.h mainuser.h \
    choosemonth.h
SOURCES += button.cpp inputreader.cpp main.cpp mainuser.cpp \
    choosemonth.cpp
